# Generated by Django 4.2.2 on 2023-07-06 12:12

import Coach.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('en_name', models.CharField(max_length=400)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Coach.models.change_coach_image_name)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(5, 'VERY_GOOD'), (4, 'GOOD'), (3, 'NORMAL'), (2, 'BAD'), (1, 'VERY_BAD')])),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='Coach.coach')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_rates', related_query_name='coach_rated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
