# Generated by Django 4.2.2 on 2023-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
