# Generated by Django 4.2.2 on 2023-07-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach", "0002_coach_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
