# Generated by Django 4.2.2 on 2023-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_coach_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_info',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
