# Generated by Django 4.2.2 on 2023-07-10 18:20

import Accounts.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0006_alter_coachsocialmedia_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='join_date',
            field=Accounts.utils.ShamsiDateField(blank=True, null=True),
        ),
    ]
