# Generated by Django 4.2.2 on 2023-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0007_coach_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='work_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
