# Generated by Django 4.2.2 on 2023-07-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0008_coach_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='Coach.coach')),
            ],
        ),
    ]
