# Generated by Django 4.2.2 on 2023-07-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='athlete_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
