# Generated by Django 4.2.2 on 2023-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_time_has_place_remain_alter_time_athlete_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='class_name',
            field=models.CharField(blank=True, default='کراسفیت', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='coach_name',
            field=models.CharField(blank=True, default='محمدرضا ذاکری', max_length=200, null=True),
        ),
    ]
