# Generated by Django 4.2.2 on 2023-07-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_time_class_name_time_coach_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='coach_name',
        ),
    ]
