# Generated by Django 4.2.2 on 2023-07-08 11:32

import Accounts.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_coach_is_active'),
        ('Classes', '0005_remove_time_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='coach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossfit_times', to='Coach.coach'),
        ),
        migrations.CreateModel(
            name='PrivateOnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Classes/Online-Class/')),
                ('slug', models.SlugField()),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_class', to='Coach.coach')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Classes/Online-Class/')),
                ('slug', models.SlugField()),
                ('start_time', Accounts.utils.ShamsiDateField(blank=True, null=True)),
                ('place_count', models.PositiveSmallIntegerField()),
                ('athlete_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_online_class', to='Coach.coach')),
            ],
        ),
    ]
