# Generated by Django 4.2.2 on 2023-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0006_time_coach_privateonlineclass_grouponlineclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='en_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
