# Generated by Django 4.2.2 on 2023-07-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0007_time_en_title_time_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouponlineclass',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateonlineclass',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
