# Generated by Django 4.2.2 on 2023-07-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0010_privateclassbenefits_groupclassbenefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOnlineClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=200)),
                ('_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='Classes.grouponlineclass')),
            ],
        ),
    ]
