# Generated by Django 4.2.2 on 2023-07-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0011_grouponlineclasstime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouponlineclasstime',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='Classes.grouponlineclass'),
        ),
    ]
