# Generated by Django 4.2.2 on 2023-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0013_grouponlineclass_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Classes/categories/')),
            ],
        ),
    ]
