# Generated by Django 4.2.2 on 2023-07-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0014_classcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.PositiveSmallIntegerField(choices=[(1, 'PRESET_CLASS'), (2, 'ONLINE_CLASS')], default=2)),
            ],
        ),
        migrations.AddField(
            model_name='grouponlineclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.classcategory'),
        ),
        migrations.AddField(
            model_name='privateonlineclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.classcategory'),
        ),
        migrations.AddField(
            model_name='time',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.classcategory'),
        ),
    ]
