# Generated by Django 4.2.2 on 2023-07-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0015_classtype_grouponlineclass_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='class_name',
        ),
        migrations.AddField(
            model_name='time',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.classtype'),
        ),
    ]
