# Generated by Django 4.2.2 on 2023-07-10 08:02

import Accounts.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_coach_slug'),
        ('Classes', '0017_alter_classtype_class_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Classes/Online-Class/')),
                ('slug', models.SlugField()),
                ('start_time', Accounts.utils.ShamsiDateField(blank=True, null=True)),
                ('place_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('athlete_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sessions_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sessions_count_in_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sessions_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_classes', to='Classes.classcategory')),
                ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_classes', to='Classes.classtype')),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_classes', to='Coach.coach')),
            ],
        ),
        migrations.RemoveField(
            model_name='grouponlineclass',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grouponlineclass',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='grouponlineclasstime',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='privateclassbenefits',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='privateonlineclass',
            name='category',
        ),
        migrations.RemoveField(
            model_name='privateonlineclass',
            name='coach',
        ),
        migrations.DeleteModel(
            name='GroupClassBenefits',
        ),
        migrations.DeleteModel(
            name='GroupOnlineClass',
        ),
        migrations.DeleteModel(
            name='GroupOnlineClassTime',
        ),
        migrations.DeleteModel(
            name='PrivateClassBenefits',
        ),
        migrations.DeleteModel(
            name='PrivateOnlineClass',
        ),
    ]
