# Generated by Django 4.2.2 on 2023-07-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0018_onlineclass_remove_grouponlineclass_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=200)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='Classes.onlineclass')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClassBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='Classes.onlineclass')),
            ],
        ),
    ]
