# Generated by Django 4.2.2 on 2023-07-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_coach_slug'),
        ('Classes', '0019_onlineclasstime_onlineclassbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclass',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_classes', to='Coach.coach'),
        ),
    ]
