# Generated by Django 4.2.2 on 2023-07-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0009_coachability'),
        ('Classes', '0020_alter_onlineclass_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossfit_times', to='Coach.coach'),
        ),
    ]
