# Generated by Django 4.2.2 on 2023-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0021_alter_time_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='class_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'کلاس حضوری'), (2, 'کلاس آنلاین گروهی'), (3, 'کلاس آنلاین خصوصی')], default=2),
        ),
    ]
