# Generated by Django 4.2.2 on 2023-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0023_timeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineclasstime',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دوشنبه'), (4, 'سه شنبه'), (5, 'چهارشنبه'), (6, 'پنجشنبه'), (7, 'جمعه')]),
        ),
    ]
