# Generated by Django 4.2.2 on 2023-08-06 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classes', '0024_alter_onlineclasstime_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClassesPreSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_classes_pre_submit_users', to='Classes.onlineclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_classes_pre_submits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
