# Generated by Django 4.2.2 on 2023-07-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_time_has_place_remain_alter_time_athlete_count'),
        ('Accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Classes.time'),
        ),
    ]
