# Generated by Django 4.2.2 on 2023-07-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_user_class_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumberValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_validation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
