# Generated by Django 4.2.2 on 2023-07-17 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0021_alter_time_coach'),
        ('Accounts', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_present', to='Classes.time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_present', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
