# Generated by Django 4.2.2 on 2023-07-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0021_alter_time_coach'),
        ('Accounts', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='Classes.time'),
        ),
    ]
