# Generated by Django 4.2.2 on 2023-07-24 07:40

import Accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0023_timeprice'),
        ('Accounts', '0012_alter_presentclass_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', Accounts.utils.ShamsiDateField(auto_now_add=True)),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='Classes.time')),
                ('time_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_payment', to='Classes.timeprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
