# Generated by Django 4.2.2 on 2023-07-25 11:45

import Accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0024_alter_onlineclasstime_day'),
        ('Accounts', '0012_alter_presentclass_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', Accounts.utils.ShamsiDateField()),
                ('time_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_payment', to='Classes.timeprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeSessionsExpire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.PositiveSmallIntegerField(default=12)),
                ('expire_date', Accounts.utils.ShamsiDateField()),
                ('time_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sessions', to='Accounts.usertimepayment')),
            ],
        ),
    ]
