# Generated by Django 4.2.2 on 2023-07-25 12:07

import Accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_usertimepayment_usertimesessionsexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimepayment',
            name='expire_date',
            field=Accounts.utils.ShamsiDateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserTimePaymentFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'پرداخت نشده'), (1, 'در انتظار پرداخت'), (2, 'پرداخت شده')], default=0)),
                ('date', Accounts.utils.ShamsiDateField(auto_now_add=True)),
                ('payment_date', Accounts.utils.ShamsiDateField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_factors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
