# Generated by Django 4.2.2 on 2023-08-02 10:23

import Accounts.utils
import Transactions.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('create_date', Accounts.utils.ShamsiDateTimeField(auto_now_add=True)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'پرداخت ناموفق'), (4, 'در انتظار تایید')], default=1)),
                ('payment_date', Accounts.utils.ShamsiDateTimeField(blank=True, null=True)),
                ('payment_way', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=[(1, 'درگاه پرداخت'), (2, 'رسید واریز')])),
                ('last_update_date', Accounts.utils.ShamsiDateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOfflinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=Transactions.utils.user_transaction_image_path)),
                ('date', Accounts.utils.ShamsiDateTimeField(auto_now_add=True)),
                ('confirmed_by_admin', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_payments', to='Transactions.usertransaction')),
            ],
        ),
    ]
