# Generated by Django 4.2.2 on 2023-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='payment_for',
            field=models.PositiveSmallIntegerField(choices=[(1, 'کلاس آنلاین خصوصی'), (2, 'کلاس آنلاین گروهی'), (3, 'تایم های حضوری کراسفیت'), (4, 'برنامه های کراسفیت'), (5, 'برنامه تغذیه')], default=3),
        ),
    ]
