# Generated by Django 4.2.2 on 2023-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_usertransaction_payment_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='payment_way',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'درگاه پرداخت'), (2, 'رسید واریز')], null=True),
        ),
    ]
