# Generated by Django 4.2.2 on 2023-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_alter_usertransaction_payment_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
