# Generated by Django 4.2.2 on 2023-08-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0004_alter_usertransaction_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='last_update_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
