# Generated by Django 4.2.2 on 2023-08-06 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classes', '0024_alter_onlineclasstime_day'),
        ('Transactions', '0007_userofflinepayment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_transactions', to='Classes.onlineclass')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_transactions', to='Transactions.usertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
