# Generated by Django 4.2.2 on 2023-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0008_onlineclasstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='payment_for',
            field=models.PositiveSmallIntegerField(choices=[(1, 'کلاس آنلاین خصوصی'), (2, 'کلاس آنلاین گروهی'), (3, 'تایم های حضوری کراسفیت'), (4, 'برنامه های کراسفیت'), (5, 'برنامه تغذیه'), (6, 'کلاس حضوری')], default=3),
        ),
    ]
