# Generated by Django 4.2.2 on 2023-07-30 11:54

import Accounts.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 7, 30, 11, 54, 30, 608680, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.PositiveSmallIntegerField(choices=[(1, 'FOR_TIME'), (2, 'AMRAP'), (3, 'EMOM'), (4, 'TABATA'), (5, 'OTHER')])),
                ('time_cap', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
