# Generated by Django 4.2.2 on 2023-07-30 12:19

import Accounts.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0004_alter_dailyplan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 7, 30, 12, 19, 3, 488814, tzinfo=datetime.timezone.utc)),
        ),
    ]
