# Generated by Django 4.2.2 on 2023-07-30 19:22

import Accounts.utils
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0005_dailyplan_description_alter_dailyplan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 7, 30, 19, 22, 16, 879713, tzinfo=datetime.timezone.utc)),
        ),
    ]
