# Generated by Django 4.2.2 on 2023-07-30 19:30

import Accounts.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0006_remove_workout_name_alter_dailyplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='has_record',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 7, 30, 19, 30, 40, 709677, tzinfo=datetime.timezone.utc)),
        ),
    ]
