# Generated by Django 4.2.2 on 2023-07-30 20:19

import Accounts.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkOuts', '0007_dailyplan_has_record_alter_dailyplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 7, 30, 20, 19, 7, 408894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.PositiveSmallIntegerField()),
                ('date', Accounts.utils.ShamsiDateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_records', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='WorkOuts.dailyplanworkout')),
            ],
        ),
    ]
