# Generated by Django 4.2.2 on 2023-08-01 09:26

import Accounts.utils
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0008_alter_dailyplan_date_userplanrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 8, 1, 9, 26, 46, 543619, tzinfo=datetime.timezone.utc)),
        ),
    ]
