# Generated by Django 4.2.2 on 2023-08-02 10:34

import Accounts.utils
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0010_alter_dailyplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 8, 2, 10, 34, 54, 854184, tzinfo=datetime.timezone.utc)),
        ),
    ]
