# Generated by Django 4.2.2 on 2023-08-03 11:05

import Accounts.utils
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOuts', '0015_alter_dailyplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=Accounts.utils.ShamsiDateField(default=datetime.datetime(2023, 8, 3, 11, 5, 47, 418888, tzinfo=datetime.timezone.utc)),
        ),
    ]
