# Generated by Django 4.2.2 on 2023-07-26 10:54

import Accounts.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coach', '0009_coachability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUsersQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=11, validators=[Accounts.utils.IranPhoneNumberValidator])),
                ('message', models.TextField()),
                ('date', Accounts.utils.ShamsiDateField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_user_questions', to='Coach.coach')),
            ],
        ),
    ]
