# Generated by Django 4.2.2 on 2023-07-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususersquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_user_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
