# Generated by Django 4.2.2 on 2023-07-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususersquestion',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
